-- Khóa ngoại bảng SANPHAM
ALTER TABLE SANPHAM ADD CONSTRAINT FK_SP_DM FOREIGN KEY (MADM) REFERENCES DANHMUC(MADM);

-- Khóa ngoại bảng NHANVIEN
ALTER TABLE NHANVIEN ADD CONSTRAINT FK_NV_TK FOREIGN KEY (MATK) REFERENCES TAIKHOAN(MATK);

-- Khóa ngoại bảng KHACHHANG
ALTER TABLE KHACHHANG ADD CONSTRAINT FK_KH_TK FOREIGN KEY (MATK) REFERENCES TAIKHOAN(MATK);

-- Khóa ngoại bảng LOSANPHAM
ALTER TABLE LOSANPHAM ADD CONSTRAINT FK_LSP_SP FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP);
ALTER TABLE LOSANPHAM ADD CONSTRAINT FK_LSP_DM FOREIGN KEY (MADM) REFERENCES DANHMUC(MADM);

-- Khóa ngoại bảng KHO
ALTER TABLE KHO ADD CONSTRAINT FK_KHO_LSP FOREIGN KEY (MALO) REFERENCES LOSANPHAM(MALO);

-- Khóa ngoại bảng PHIEUNHAP
ALTER TABLE PHIEUNHAP ADD CONSTRAINT FK_PN_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV);
ALTER TABLE PHIEUNHAP ADD CONSTRAINT FK_PN_NCC FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP(MANCC);

-- Khóa ngoại bảng CTPN
ALTER TABLE CTPN ADD CONSTRAINT FK_CTPN_PN FOREIGN KEY (MAPN) REFERENCES PHIEUNHAP(MAPN);
ALTER TABLE CTPN ADD CONSTRAINT FK_CTPN_LSP FOREIGN KEY (MALO) REFERENCES LOSANPHAM(MALO);

-- Khóa ngoại bảng HOADON
ALTER TABLE HOADON ADD CONSTRAINT FK_HD_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV);
ALTER TABLE HOADON ADD CONSTRAINT FK_HD_KH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH);

-- Khóa ngoại bảng CTHD
ALTER TABLE CTHD ADD CONSTRAINT FK_CTHD_HD FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD);
ALTER TABLE CTHD ADD CONSTRAINT FK_CTHD_LSP FOREIGN KEY (MALO) REFERENCES LOSANPHAM(MALO);

-- Khóa ngoại bảng THANHTOAN
ALTER TABLE THANHTOAN ADD CONSTRAINT FK_TT_HD FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD);

-- Khóa ngoại bảng PHIEUTRA_NCC
ALTER TABLE PHIEUTRA_NCC ADD CONSTRAINT FK_PTNCC_PN FOREIGN KEY (MAPN) REFERENCES PHIEUNHAP(MAPN);
ALTER TABLE PHIEUTRA_NCC ADD CONSTRAINT FK_PTNCC_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV);

-- Khóa ngoại bảng CTPT_NCC
ALTER TABLE CTPT_NCC ADD CONSTRAINT FK_CTPTNCC_PT FOREIGN KEY (MAPT_NCC) REFERENCES PHIEUTRA_NCC(MAPT_NCC);
ALTER TABLE CTPT_NCC ADD CONSTRAINT FK_CTPTNCC_LSP FOREIGN KEY (MALO) REFERENCES LOSANPHAM(MALO);

-- Khóa ngoại bảng PHIEUTRA_KH
ALTER TABLE PHIEUTRA_KH ADD CONSTRAINT FK_PTKH_HD FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD);
ALTER TABLE PHIEUTRA_KH ADD CONSTRAINT FK_PTKH_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV);

-- Khóa ngoại bảng CTPT_KH
ALTER TABLE CTPT_KH ADD CONSTRAINT FK_CTPTKH_PT FOREIGN KEY (MAPT_KH) REFERENCES PHIEUTRA_KH(MAPT_KH);
ALTER TABLE CTPT_KH ADD CONSTRAINT FK_CTPTKH_LSP FOREIGN KEY (MALO) REFERENCES LOSANPHAM(MALO);

--Khóa ngoại bảng DIEMTL
ALTER TABLE DIEMTL ADD CONSTRAINT FK_DIEMTL_KH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH);
ALTER TABLE DIEMTL ADD CONSTRAINT FK_DIEMTL_HD FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD);
ALTER TABLE DIEMTL ADD CONSTRAINT CHK_LOAIGD_DIEMTL CHECK (LOAIGD IN ('CONG_DIEM', 'TRU_DIEM'));
