CREATE TABLE DANHMUC (
    MADM VARCHAR2(20) PRIMARY KEY,
    TENDM VARCHAR2(100),
    MOTA VARCHAR2(255)
);

CREATE TABLE NHACUNGCAP (
    MANCC VARCHAR2(20) PRIMARY KEY,
    TENNCC VARCHAR2(100),
    SDT VARCHAR2(10),
    GMAIL VARCHAR2(100),
    DIACHI VARCHAR2(255)
);

CREATE TABLE TAIKHOAN (
    MATK VARCHAR2(20) PRIMARY KEY,
    VAITRO VARCHAR2(50),
    PASSWORD VARCHAR2(255),
    SDT VARCHAR2(10),
    NGAYTAO DATE DEFAULT SYSDATE
);

CREATE TABLE SANPHAM (
    MASP VARCHAR2(20) PRIMARY KEY,
    MADM VARCHAR2(20),
    TENSANPHAM VARCHAR2(100),
    DVT VARCHAR2(50),
    CONGDUNG VARCHAR2(255),
    GIABAN NUMBER,
    CONSTRAINT FK_SP_DM FOREIGN KEY (MADM) REFERENCES DANHMUC(MADM)
);

CREATE TABLE NHANVIEN (
    MANV VARCHAR2(20) PRIMARY KEY,
    MATK VARCHAR2(20),
    TENNV VARCHAR2(100),
    GIOITINH VARCHAR2(10),
    SDT VARCHAR2(10),
    GMAIL VARCHAR2(100),
    CONSTRAINT FK_NV_TK FOREIGN KEY (MATK) REFERENCES TAIKHOAN(MATK)
);

CREATE TABLE DIEMTL (
    MADTL VARCHAR2(20) PRIMARY KEY,
    LOAIGD VARCHAR2(50),
    SL NUMBER
);

CREATE TABLE KHACHHANG (
    MAKH VARCHAR2(20) PRIMARY KEY,
    MATK VARCHAR2(20),
    MADTL VARCHAR2(20),
    TENKH VARCHAR2(100),
    GIOITINH VARCHAR2(10),
    SDT VARCHAR2(10),
    CONSTRAINT FK_KH_TK FOREIGN KEY (MATK) REFERENCES TAIKHOAN(MATK),
    CONSTRAINT FK_KH_DTL FOREIGN KEY (MADTL) REFERENCES DIEMTL(MADTL)
);

CREATE TABLE LOSANPHAM (
    MALO VARCHAR2(20) PRIMARY KEY,
    MASP VARCHAR2(20),
    MADM VARCHAR2(20),
    NGAYNHAP DATE,
    HSD DATE,
    SLSP NUMBER,
    CONSTRAINT FK_LSP_SP FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP),
    CONSTRAINT FK_LSP_DM FOREIGN KEY (MADM) REFERENCES DANHMUC(MADM)
);

CREATE TABLE KHO (
    MAKHO VARCHAR2(20) PRIMARY KEY,
    MALO VARCHAR2(20),
    SLTON NUMBER,
    DVSP VARCHAR2(50),
    CONSTRAINT FK_KHO_LSP FOREIGN KEY (MALO) REFERENCES LOSANPHAM(MALO)
);

CREATE TABLE PHIEUNHAP (
    MAPN VARCHAR2(20) PRIMARY KEY,
    MANV VARCHAR2(20),
    MANCC VARCHAR2(20),
    NGAYNHAP DATE,
    TONGTIEN NUMBER,
    CONSTRAINT FK_PN_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
    CONSTRAINT FK_PN_NCC FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP(MANCC)
);

CREATE TABLE CTPN (
    MAPN VARCHAR2(20),
    MALO VARCHAR2(20),
    SL NUMBER,
    GIANHAP NUMBER,
    DVT VARCHAR2(50),
    GHICHU VARCHAR2(255),
    THANHTIEN NUMBER,
    PRIMARY KEY (MAPN, MALO),
    CONSTRAINT FK_CTPN_PN FOREIGN KEY (MAPN) REFERENCES PHIEUNHAP(MAPN),
    CONSTRAINT FK_CTPN_LSP FOREIGN KEY (MALO) REFERENCES LOSANPHAM(MALO)
);

CREATE TABLE HOADON (
    MAHD VARCHAR2(20) PRIMARY KEY,
    MANV VARCHAR2(20),
    MAKH VARCHAR2(20),
    NGAYBAN DATE,
    TONGTIEN NUMBER,
    DIEMSUDUNG NUMBER,
    TIENTHANHTOAN NUMBER,
    CONSTRAINT FK_HD_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
    CONSTRAINT FK_HD_KH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
);

CREATE TABLE CTHD (
    MAHD VARCHAR2(20),
    MALO VARCHAR2(20),
    SL NUMBER,
    MAHD_CT VARCHAR2(20),
    DONGIA NUMBER,
    THANHTIEN NUMBER,
    GHICHU VARCHAR2(255),
    PRIMARY KEY (MAHD, MALO),
    CONSTRAINT FK_CTHD_HD FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD),
    CONSTRAINT FK_CTHD_LSP FOREIGN KEY (MALO) REFERENCES LOSANPHAM(MALO)
);

CREATE TABLE THANHTOAN (
    MATT VARCHAR2(20) PRIMARY KEY,
    MAHD VARCHAR2(20),
    MAKH VARCHAR2(20),
    PHUONGTHUC VARCHAR2(50),
    TRANGTHAI VARCHAR2(50),
    CONSTRAINT FK_TT_HD FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD),
    CONSTRAINT FK_TT_KH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
);

CREATE TABLE PHIEUTRA_NCC (
    MAPT_NCC VARCHAR2(20) PRIMARY KEY,
    MAPN VARCHAR2(20),
    MANV VARCHAR2(20),
    NGAYTRA DATE,
    LYDOTRA VARCHAR2(255),
    TONGTIEN NUMBER,
    CONSTRAINT FK_PTNCC_PN FOREIGN KEY (MAPN) REFERENCES PHIEUNHAP(MAPN),
    CONSTRAINT FK_PTNCC_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);

CREATE TABLE CTPT_NCC (
    MACTPT_NCC VARCHAR2(20) PRIMARY KEY,
    MAPT_NCC VARCHAR2(20),
    MASP VARCHAR2(20),
    MAPN VARCHAR2(20),
    SL NUMBER,
    DONGIATRA NUMBER,
    THANHTIEN NUMBER,
    CONSTRAINT FK_CTPTNCC_PT FOREIGN KEY (MAPT_NCC) REFERENCES PHIEUTRA_NCC(MAPT_NCC),
    CONSTRAINT FK_CTPTNCC_SP FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)
);

CREATE TABLE PHIEUTRA_KH (
    MAPT_KH VARCHAR2(20) PRIMARY KEY,
    MAHD VARCHAR2(20),
    MANV VARCHAR2(20),
    NGAYTRA DATE,
    LYDOTRA VARCHAR2(255),
    TONGTIENHOAN NUMBER,
    CONSTRAINT FK_PTKH_HD FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD),
    CONSTRAINT FK_PTKH_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);

CREATE TABLE CTPT_KH (
    MACTPT_KH VARCHAR2(20) PRIMARY KEY,
    MAPT_KH VARCHAR2(20),
    MASP VARCHAR2(20),
    SL NUMBER,
    DONGIAHOAN NUMBER,
    THANHTIEN NUMBER,
    CONSTRAINT FK_CTPTKH_PT FOREIGN KEY (MAPT_KH) REFERENCES PHIEUTRA_KH(MAPT_KH),
    CONSTRAINT FK_CTPTKH_SP FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)
);

alter table TAIKHOAN add IS_FIRST_LOGIN number(1) default 1;

--- test data
SELECT * FROM TAIKHOAN;
