CREATE TABLE DANHMUC (
    MADM VARCHAR2(20) PRIMARY KEY,
    TENDM VARCHAR2(100),
    MOTA VARCHAR2(255),
    TRANGTHAI VARCHAR2(50)
);

CREATE TABLE NHACUNGCAP (
    MANCC VARCHAR2(20) PRIMARY KEY,
    TENNCC VARCHAR2(100),
    SDT VARCHAR2(10),
    EMAIL VARCHAR2(100),
    DIACHI VARCHAR2(255)
);

CREATE TABLE TAIKHOAN (
    MATK VARCHAR2(20) PRIMARY KEY,
    VAITRO VARCHAR2(50),
    PASSWORD VARCHAR2(255),
    SDT VARCHAR2(10),
    NGAYTAO DATE DEFAULT SYSDATE,
    IS_FIRST_LOGIN NUMBER(1) DEFAULT 1,
    EMAIL VARCHAR2(100),
    TRANGTHAI VARCHAR2(50)
);

CREATE TABLE SANPHAM (
    MASP VARCHAR2(20) PRIMARY KEY,
    MADM VARCHAR2(20),
    TENSANPHAM VARCHAR2(100),
    DVT VARCHAR2(50),
    CONGDUNG VARCHAR2(255),
    THANHPHAN VARCHAR2(500),
    GIABAN NUMBER DEFAULT 0 NOT NULL,
    TRANGTHAI VARCHAR2(50)
);


CREATE TABLE NHANVIEN (
    MANV VARCHAR2(20) PRIMARY KEY,
    MATK VARCHAR2(20),
    TENNV VARCHAR2(100),
    GIOITINH VARCHAR2(10),
    NGAYSINH DATE,
    SDT VARCHAR2(10),
    CHUCVU VARCHAR2(50),
    TRANGTHAI VARCHAR2(50)
);

CREATE TABLE DIEMTL (
    MADTL VARCHAR2(20) PRIMARY KEY,
    MAKH VARCHAR2(20),
    MAHD VARCHAR2(20),
    DIEMTHAYDOI NUMBER,
    NGAYGD DATE DEFAULT SYSDATE,
    LOAIGD VARCHAR2(50),
    GHICHU VARCHAR2(255)
);

CREATE TABLE KHACHHANG (
    MAKH VARCHAR2(20) PRIMARY KEY,
    MATK VARCHAR2(20),
    TENKH VARCHAR2(100),
    GIOITINH VARCHAR2(10),
    NGAYSINH DATE,
    SDT VARCHAR2(10),
    TONGDOANHTHU NUMBER DEFAULT 0,
    DIEMTICHLUY NUMBER DEFAULT 0,
    HANGTV VARCHAR2(50) DEFAULT 'THANH VIEN'
);

CREATE TABLE KHO (
    MAKHO VARCHAR2(20) PRIMARY KEY,
    LOAIKHO VARCHAR2(20),
    SLTON NUMBER,
    DVSP VARCHAR2(50)
);

CREATE TABLE LOSANPHAM (
    MALO VARCHAR2(20) PRIMARY KEY,
    MASP VARCHAR2(20),
    MAKHO VARCHAR2(20),
    NGAYSX DATE,
    NGAYNHAP DATE,
    HSD DATE,
    SLSP NUMBER,
    TRANGTHAI VARCHAR2(50)
);

CREATE TABLE PHIEUNHAP (
    MAPN VARCHAR2(20) PRIMARY KEY,
    MANV VARCHAR2(20),
    MANCC VARCHAR2(20),
    NGAYNHAP DATE,
    TONGTIEN NUMBER,
    TRANGTHAI VARCHAR2(50) DEFAULT 'KHOI TAO'
);

CREATE TABLE CTPN (
    MAPN VARCHAR2(20),
    MALO VARCHAR2(20),
    SL NUMBER,
    GIANHAP NUMBER,
    DVT VARCHAR2(50),
    GHICHU VARCHAR2(255),
    THANHTIEN NUMBER,
    PRIMARY KEY (MAPN, MALO)
);

CREATE TABLE HOADON (
    MAHD VARCHAR2(20) PRIMARY KEY,
    MANV VARCHAR2(20),
    MAKH VARCHAR2(20),
    NGAYBAN DATE,
    TONGTIEN NUMBER,
    DIEMSUDUNG NUMBER,
    TIENTHANHTOAN NUMBER,
    TRANGTHAI VARCHAR2(50) DEFAULT 'KHOI_TAO'
);

CREATE TABLE CTHD (
    MAHD VARCHAR2(20),
    MALO VARCHAR2(20),
    SL NUMBER,
    DONGIA NUMBER,
    THANHTIEN NUMBER,
    GHICHU VARCHAR2(255),
    PRIMARY KEY (MAHD, MALO)
);

CREATE TABLE THANHTOAN (
    MATT VARCHAR2(20) PRIMARY KEY,
    MAHD VARCHAR2(20),
    PHUONGTHUC VARCHAR2(50),
    TRANGTHAI VARCHAR2(50)
);

CREATE TABLE PHIEUTRA_NCC (
    MAPT_NCC VARCHAR2(20) PRIMARY KEY,
    MAPN VARCHAR2(20),
    MANV VARCHAR2(20),
    NGAYTRA DATE,
    LYDOTRA VARCHAR2(255),
    TONGTIEN NUMBER
);

CREATE TABLE CTPT_NCC (
    MAPT_NCC VARCHAR2(20),
    MALO VARCHAR2(20),
    SL NUMBER,
    DONGIATRA NUMBER,
    THANHTIEN NUMBER,
    PRIMARY KEY (MAPT_NCC, MALO)
);

CREATE TABLE PHIEUTRA_KH (
    MAPT_KH VARCHAR2(20) PRIMARY KEY,
    MAHD VARCHAR2(20),
    MANV VARCHAR2(20),
    NGAYTRA DATE,
    LYDOTRA VARCHAR2(255),
    TONGTIENHOAN NUMBER
);

CREATE TABLE CTPT_KH (
    MAPT_KH VARCHAR2(20),
    MALO VARCHAR2(20),
    SL NUMBER,
    DONGIAHOAN NUMBER,
    THANHTIEN NUMBER,
    PRIMARY KEY (MAPT_KH, MALO)
);

CREATE SEQUENCE SEQ_DANHMUC START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_KHO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_NHACUNGCAP START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_SANPHAM START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_LOSANPHAM START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE SEQ_KHACHHANG START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_NHANVIEN START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TAIKHOAN START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE SEQ_HOADON START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PHIEUNHAP START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PHIEUTRA_NCC START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PHIEUTRA_KH START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_THANHTOAN START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_DIEMTL START WITH 1 INCREMENT BY 1;

