CREATE TABLE DANHMUC (
    MADM VARCHAR2(20) PRIMARY KEY,
    TENDM VARCHAR2(100),
    MOTA VARCHAR2(255),
    TYLELOINHUAN NUMBER(5,2)
);

CREATE TABLE NHACUNGCAP (
    MANCC VARCHAR2(20) PRIMARY KEY,
    TENNCC VARCHAR2(100),
    SDT VARCHAR2(10),
    EMAIL VARCHAR2(100),
    DIACHI VARCHAR2(255)
);

CREATE TABLE TAIKHOAN (
    MATK VARCHAR2(20) PRIMARY KEY,
    VAITRO VARCHAR2(50),
    PASSWORD VARCHAR2(255),
    SDT VARCHAR2(10),
    NGAYTAO DATE DEFAULT SYSDATE,
    IS_FIRST_LOGIN NUMBER(1) DEFAULT 1,
    EMAIL VARCHAR2(100)
);

CREATE TABLE SANPHAM (
    MASP VARCHAR2(20) PRIMARY KEY,
    MADM VARCHAR2(20),
    TENSANPHAM VARCHAR2(100),
    DVT VARCHAR2(50),
    CONGDUNG VARCHAR2(255),
    THANHPHAN VARCHAR2(500),
    GIABAN NUMBER DEFAULT 0 NOT NULL,
    IS_MANUAL_PRICE NUMBER(1) DEFAULT 0
);

/*CREATE TABLE HOATCHAT (
    MAHC VARCHAR2(20) PRIMARY KEY,
    TENHC VARCHAR2(100) NOT NULL,
    MOTA VARCHAR2(255)
);

CREATE TABLE CT_HOATCHAT (
    MASP VARCHAR2(20),
    MAHC VARCHAR2(20),
    HAMLUONG VARCHAR2(100),
    PRIMARY KEY (MASP, MAHC)
);*/

CREATE TABLE NHANVIEN (
    MANV VARCHAR2(20) PRIMARY KEY,
    MATK VARCHAR2(20),
    TENNV VARCHAR2(100),
    GIOITINH VARCHAR2(10),
    NGAYSINH DATE,
    SDT VARCHAR2(10),
    CHUCVU VARCHAR2(50)
);

CREATE TABLE DIEMTL (
    MADTL VARCHAR2(20) PRIMARY KEY,
    LOAIGD VARCHAR2(50),
    SL NUMBER
);

CREATE TABLE KHACHHANG (
    MAKH VARCHAR2(20) PRIMARY KEY,
    MATK VARCHAR2(20),
    MADTL VARCHAR2(20),
    TENKH VARCHAR2(100),
    GIOITINH VARCHAR2(10),
    NGAYSINH DATE,
    SDT VARCHAR2(10),
    TONGDOANHTHU NUMBER DEFAULT 0,
    HANGTV VARCHAR2(50) DEFAULT 'THANH VIEN'
);

CREATE TABLE LOSANPHAM (
    MALO VARCHAR2(20) PRIMARY KEY,
    MASP VARCHAR2(20),
    MADM VARCHAR2(20),
    NGAYSX DATE,
    NGAYNHAP DATE,
    HSD DATE,
    SLSP NUMBER,
    TRANGTHAI VARCHAR2(50)
);

CREATE TABLE KHO (
    MAKHO VARCHAR2(20) PRIMARY KEY,
    MALO VARCHAR2(20),
    SLTON NUMBER,
    DVSP VARCHAR2(50)
);

CREATE TABLE PHIEUNHAP (
    MAPN VARCHAR2(20) PRIMARY KEY,
    MANV VARCHAR2(20),
    MANCC VARCHAR2(20),
    NGAYNHAP DATE,
    TONGTIEN NUMBER,
    TRANGTHAI VARCHAR2(50) DEFAULT 'KHOI TAO'
);

CREATE TABLE CTPN (
    MAPN VARCHAR2(20),
    MALO VARCHAR2(20),
    SL NUMBER,
    GIANHAP NUMBER,
    DVT VARCHAR2(50),
    GHICHU VARCHAR2(255),
    THANHTIEN NUMBER,
    PRIMARY KEY (MAPN, MALO)
);

CREATE TABLE HOADON (
    MAHD VARCHAR2(20) PRIMARY KEY,
    MANV VARCHAR2(20),
    MAKH VARCHAR2(20),
    NGAYBAN DATE,
    TONGTIEN NUMBER,
    DIEMSUDUNG NUMBER,
    TIENTHANHTOAN NUMBER,
    TRANGTHAI VARCHAR2(50) DEFAULT 'KHOI TAO'
);

CREATE TABLE CTHD (
    MAHD VARCHAR2(20),
    MALO VARCHAR2(20),
    SL NUMBER,
    MAHD_CT VARCHAR2(20),
    DONGIA NUMBER,
    THANHTIEN NUMBER,
    GHICHU VARCHAR2(255),
    PRIMARY KEY (MAHD, MALO)
);

CREATE TABLE THANHTOAN (
    MATT VARCHAR2(20) PRIMARY KEY,
    MAHD VARCHAR2(20),
    PHUONGTHUC VARCHAR2(50),
    TRANGTHAI VARCHAR2(50)
);

CREATE TABLE PHIEUTRA_NCC (
    MAPT_NCC VARCHAR2(20) PRIMARY KEY,
    MAPN VARCHAR2(20),
    MANV VARCHAR2(20),
    NGAYTRA DATE,
    LYDOTRA VARCHAR2(255),
    TONGTIEN NUMBER
);

CREATE TABLE CTPT_NCC (
    MACTPT_NCC VARCHAR2(20) PRIMARY KEY,
    MAPT_NCC VARCHAR2(20),
    MALO VARCHAR2(20),
    SL NUMBER,
    DONGIATRA NUMBER,
    THANHTIEN NUMBER
);

CREATE TABLE PHIEUTRA_KH (
    MAPT_KH VARCHAR2(20) PRIMARY KEY,
    MAHD VARCHAR2(20),
    MANV VARCHAR2(20),
    NGAYTRA DATE,
    LYDOTRA VARCHAR2(255),
    TONGTIENHOAN NUMBER
);

CREATE TABLE CTPT_KH (
    MACTPT_KH VARCHAR2(20) PRIMARY KEY,
    MAPT_KH VARCHAR2(20),
    MALO VARCHAR2(20),
    SL NUMBER,
    DONGIAHOAN NUMBER,
    THANHTIEN NUMBER
);

/*CREATE TABLE LOG_NHAPHANG (
    LOG_ID VARCHAR2(20) PRIMARY KEY,
    MAPN VARCHAR2(20),
    THOIGIAN DATE DEFAULT SYSDATE,
    SOLUONG_CU NUMBER,
    SOLUONG_MOI NUMBER
);

CREATE TABLE LOG_BANHANG (
    LOG_ID VARCHAR2(20) PRIMARY KEY,
    MAHD VARCHAR2(20),
    THOIGIAN DATE DEFAULT SYSDATE,
    TONGTIEN_CU NUMBER,
    TONGTIEN_MOI NUMBER
);*/

COMMIT;