DROP TABLE CTPT_KH CASCADE CONSTRAINTS;
DROP TABLE PHIEUTRA_KH CASCADE CONSTRAINTS;
DROP TABLE CTPT_NCC CASCADE CONSTRAINTS;
DROP TABLE PHIEUTRA_NCC CASCADE CONSTRAINTS;
DROP TABLE THANHTOAN CASCADE CONSTRAINTS;
DROP TABLE CTHD CASCADE CONSTRAINTS;
DROP TABLE HOADON CASCADE CONSTRAINTS;
DROP TABLE CTPN CASCADE CONSTRAINTS;
DROP TABLE PHIEUNHAP CASCADE CONSTRAINTS;
DROP TABLE KHO CASCADE CONSTRAINTS;
DROP TABLE LOSANPHAM CASCADE CONSTRAINTS;
DROP TABLE KHACHHANG CASCADE CONSTRAINTS;
DROP TABLE DIEMTL CASCADE CONSTRAINTS;
DROP TABLE NHANVIEN CASCADE CONSTRAINTS;
DROP TABLE SANPHAM CASCADE CONSTRAINTS;
DROP TABLE TAIKHOAN CASCADE CONSTRAINTS;
DROP TABLE NHACUNGCAP CASCADE CONSTRAINTS;
DROP TABLE DANHMUC CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_DANHMUC;
DROP SEQUENCE SEQ_KHO;
DROP SEQUENCE SEQ_NHACUNGCAP;
DROP SEQUENCE SEQ_SANPHAM;
DROP SEQUENCE SEQ_LOSANPHAM;
DROP SEQUENCE SEQ_KHACHHANG;
DROP SEQUENCE SEQ_NHANVIEN;
DROP SEQUENCE SEQ_TAIKHOAN;
DROP SEQUENCE SEQ_HOADON;
DROP SEQUENCE SEQ_PHIEUNHAP;
DROP SEQUENCE SEQ_PHIEUTRA_NCC;
DROP SEQUENCE SEQ_PHIEUTRA_KH;
DROP SEQUENCE SEQ_THANHTOAN;
DROP SEQUENCE SEQ_DIEMTL;


COMMIT;