
CREATE TABLE DANHMUC (
    MADM    VARCHAR2(10) PRIMARY KEY,
    TENDM   VARCHAR2(100) NOT NULL,
    MOTA    VARCHAR2(255)
);

-- 2. SANPHAM
CREATE TABLE SANPHAM (
    MASP        VARCHAR2(10) PRIMARY KEY,
    TENSANPHAM  VARCHAR2(200) NOT NULL,
    MADM        VARCHAR2(10),
    DVT         VARCHAR2(50),
    GIABAN      NUMBER(15,2),
    CONGDUNG    VARCHAR2(500),
    CONSTRAINT fk_sp_dm FOREIGN KEY (MADM) REFERENCES DANHMUC(MADM)
);

-- 3. KHO
CREATE TABLE KHO (
    MAKHO   VARCHAR2(10) PRIMARY KEY,
    TENKHO  VARCHAR2(100) NOT NULL,
    MALO    VARCHAR2(10),
    SLTON   NUMBER(10),
    DVSP    VARCHAR2(50)
);

-- 4. LOSANPHAM
CREATE TABLE LOSANPHAM (
    MALO        VARCHAR2(10) PRIMARY KEY,
    MASP        VARCHAR2(10),
    MAKHO       VARCHAR2(10),
    MADM        VARCHAR2(10),
    NGAYNHAP    DATE,
    HSD         DATE,
    SLSP        NUMBER(10),
    GIANHAP     NUMBER(15,2),
    CONSTRAINT fk_lo_sp   FOREIGN KEY (MASP)  REFERENCES SANPHAM(MASP),
    CONSTRAINT fk_lo_kho  FOREIGN KEY (MAKHO) REFERENCES KHO(MAKHO),
    CONSTRAINT fk_lo_dm   FOREIGN KEY (MADM)  REFERENCES DANHMUC(MADM)
);

-- 5. NHACUNGCAP
CREATE TABLE NHACUNGCAP (
    MANCC   VARCHAR2(10) PRIMARY KEY,
    TENNCC  VARCHAR2(200) NOT NULL,
    GMAIL   VARCHAR2(100),
    SDT     VARCHAR2(20),
    DIACHI  VARCHAR2(255)
);

-- 6. NHANVIEN
CREATE TABLE NHANVIEN (
    MANV    VARCHAR2(10) PRIMARY KEY,
    TENNV   VARCHAR2(100) NOT NULL,
    GIOITINH VARCHAR2(10),
    SDT     VARCHAR2(20),
    GMAIL   VARCHAR2(100)
);

-- 7. TAIKHOAN
CREATE TABLE TAIKHOAN (
    MATK        VARCHAR2(10) PRIMARY KEY,
    MANV        VARCHAR2(10),
    VAITRO      VARCHAR2(50),
    PASSWORD    VARCHAR2(255) NOT NULL,
    SDT         VARCHAR2(20),
    NGAYTAO     DATE DEFAULT SYSDATE,
    CONSTRAINT fk_tk_nv FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);

-- 8. PHIEUNHAP
CREATE TABLE PHIEUNHAP (
    MAPN        VARCHAR2(10) PRIMARY KEY,
    MANV        VARCHAR2(10),
    MANCC       VARCHAR2(10),
    NGAYNHAP    DATE DEFAULT SYSDATE,
    TONGTIEN    NUMBER(15,2),
    CONSTRAINT fk_pn_nv  FOREIGN KEY (MANV)  REFERENCES NHANVIEN(MANV),
    CONSTRAINT fk_pn_ncc FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP(MANCC)
);

-- 9. CTPN (Chi tiet phieu nhap)
CREATE TABLE CTPN (
    MAPN        VARCHAR2(10),
    MALO        VARCHAR2(10),
    MASP        VARCHAR2(10),
    SL          NUMBER(10),
    DVT         VARCHAR2(50),
    GIANHAP     NUMBER(15,2),
    THANHTIEN   NUMBER(15,2),
    GHICHU      VARCHAR2(255),
    PRIMARY KEY (MAPN, MALO),
    CONSTRAINT fk_ctpn_pn FOREIGN KEY (MAPN) REFERENCES PHIEUNHAP(MAPN),
    CONSTRAINT fk_ctpn_lo FOREIGN KEY (MALO) REFERENCES LOSANPHAM(MALO)
);

-- 10. PHIEUTRA_NCC
CREATE TABLE PHIEUTRA_NCC (
    MAPT_NCC    VARCHAR2(10) PRIMARY KEY,
    MAPN        VARCHAR2(10),
    MANV        VARCHAR2(10),
    MANCC       VARCHAR2(10),
    NGAYTRA     DATE DEFAULT SYSDATE,
    LYDOTRA     VARCHAR2(255),
    TONGTIEN    NUMBER(15,2),
    CONSTRAINT fk_ptncc_pn  FOREIGN KEY (MAPN)  REFERENCES PHIEUNHAP(MAPN),
    CONSTRAINT fk_ptncc_nv  FOREIGN KEY (MANV)  REFERENCES NHANVIEN(MANV),
    CONSTRAINT fk_ptncc_ncc FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP(MANCC)
);

-- 11. CTPT_NCC
CREATE TABLE CTPT_NCC (
    MAPT_NCC    VARCHAR2(10),
    MASP        VARCHAR2(10),
    MACTPT_NCC  VARCHAR2(10),
    DONGIA_TRA  NUMBER(15,2),
    SL          NUMBER(10),
    THANHTIEN   NUMBER(15,2),
    PRIMARY KEY (MAPT_NCC, MASP),
    CONSTRAINT fk_ctptncc_pt FOREIGN KEY (MAPT_NCC) REFERENCES PHIEUTRA_NCC(MAPT_NCC)
);

-- 12. KHACHHANG
CREATE TABLE KHACHHANG (
    MAKH        VARCHAR2(10) PRIMARY KEY,
    TENKH       VARCHAR2(100) NOT NULL,
    SDT         VARCHAR2(20) UNIQUE NOT NULL,
    GIOITINH    VARCHAR2(10),
    MATK        VARCHAR2(10),
    CONSTRAINT fk_kh_tk FOREIGN KEY (MATK) REFERENCES TAIKHOAN(MATK)
);

-- 13. DIEMTL (Diem tich luy)
CREATE TABLE DIEMTL (
    MADTL       VARCHAR2(10) PRIMARY KEY,
    MAKH        VARCHAR2(10),
    LOAIGD      VARCHAR2(50),
    SL          NUMBER(10) DEFAULT 0,
    CONSTRAINT fk_dtl_kh FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
);

-- 14. HOADON
CREATE TABLE HOADON (
    MAHD        VARCHAR2(10) PRIMARY KEY,
    MANV        VARCHAR2(10),
    MAKH        VARCHAR2(10),
    NGAYBAN     DATE DEFAULT SYSDATE,
    TONGTIEN    NUMBER(15,2),
    TIENTHANHTOAN NUMBER(15,2),
    DIEMSUDUNG  NUMBER(10) DEFAULT 0,
    CONSTRAINT fk_hd_nv FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
    CONSTRAINT fk_hd_kh FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
);

-- 15. CTHD (Chi tiet hoa don)
CREATE TABLE CTHD (
    MAHD        VARCHAR2(10),
    MALO        VARCHAR2(10),
    GHICHU      VARCHAR2(255),
    SL          NUMBER(10),
    DONGIA      NUMBER(15,2),
    THANHTIEN   NUMBER(15,2),
    PRIMARY KEY (MAHD, MALO),
    CONSTRAINT fk_cthd_hd FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD),
    CONSTRAINT fk_cthd_lo FOREIGN KEY (MALO) REFERENCES LOSANPHAM(MALO)
);

-- 16. THANHTOAN
CREATE TABLE THANHTOAN (
    MATT        VARCHAR2(10) PRIMARY KEY,
    MAHD        VARCHAR2(10),
    TRANGTHAI   VARCHAR2(50),
    PHUONGTHUC  VARCHAR2(50),
    CONSTRAINT fk_tt_hd FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD)
);

-- 17. PHIEUTRA_KH
CREATE TABLE PHIEUTRA_KH (
    MAPT_KH     VARCHAR2(10) PRIMARY KEY,
    MAHD        VARCHAR2(10),
    MAPT_KH2    VARCHAR2(10),
    MANV        VARCHAR2(10),
    NGAYTRA     DATE DEFAULT SYSDATE,
    LYDOTRA     VARCHAR2(255),
    TONGTIENHOAN NUMBER(15,2),
    CONSTRAINT fk_ptkh_hd FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD),
    CONSTRAINT fk_ptkh_nv FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);

-- 18. CTPT_KH
CREATE TABLE CTPT_KH (
    MACTPT_KH   VARCHAR2(10) PRIMARY KEY,
    MAPT_KH     VARCHAR2(10),
    MASP        VARCHAR2(10),
    SL          NUMBER(10),
    THANHTIEN   NUMBER(15,2),
    DONGIAHOAN  NUMBER(15,2),
    CONSTRAINT fk_ctptkh_pt FOREIGN KEY (MAPT_KH) REFERENCES PHIEUTRA_KH(MAPT_KH)
);

-- =============================================
-- KIỂM TRA TẤT CẢ BẢNG ĐÃ TẠO
-- =============================================
SELECT TABLE_NAME FROM USER_TABLES ORDER BY TABLE_NAME;


select * from khachhang;