spring.application.name=backend
# connect Database Oracle
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/ORCLPDB
spring.datasource.username=PHARMA
spring.datasource.password=123456
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

# Port Server
server.port=8080

# Mail Sender
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=trucmai19102006@gmail.com
# App Password
spring.mail.password=rgaeqjifycfftoop
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# JWT
jwt.secret=SecretStringForPharmacyManagementSystem2026

# Cấu hình Gemini AI API Key
gemini.api.key=AIzaSyBn17EEusKEjD9DYXPYt5AYoTj_erUQOa8
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite:generateContent